config/routes.rb
Picker::Application.routes.draw do
  resources :products do
    member do
      get 'up_vote'
      get 'down_vote'
    end
  end
  root :to => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_presence_of :price, :description, :votes
	serialize :images

	def self.new_from_url(url)
		doc = Nokogiri(open(url))
		price = doc.search('h2').to_s[/\$(\d+)/].gsub('$',"")
		title = doc.title
		description = doc.search('#userbody').to_s.split('<!--')[0].gsub(%r{</?[^>]+?>}, '').gsub(/\n/," ").strip
		if doc.to_s.match('maps.google.com')
			map_url = doc.search('small a')[0]['href'].match('maps.google.com').string
		end
		images = doc.search('table img').map {|i| i['src']}
		new({ :price => price , :title => title, :description => description, :map_url => map_url, :images => images })
	end
end

test = {
	val1: :test1,
	val2: :foobar,
}

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/product_controller.rb
class ProductsController < ApplicationController
  require 'open-uri'

    def index
      @products = Product.all
    end

    def up_vote
      @product = Product.find(params[:id])
      @product.votes += 1
      if @product.save
		flash[:notice] = "Success! Your product has been saved."
		redirect_to :action => 'index'
	  end
    end

    def down_vote
      @product = Product.find(params[:id])
      @product.votes -= 1
      @product.save
      if @product.save
		flash[:notice] = "Success! Your product has been saved."
		redirect_to :action => 'index'
	  end
    end

	def show
	  @product = Product.find(params[:id])
	end

	def new
	  @product = Product.new
	end

	def create
		if params['url']
		  p = get_info(params['url'])
		  @product = Product.new(price: p[:price], description: p[:description], title: p[:title], map_url: p[:map_url])
   		  if @product.save
		   	flash[:notice] = "Success! Your product has been saved."
		  	redirect_to @product
		  else
		  	render :action => 'new'
		  end
		end
	end

	def get_info(url)
		doc = Nokogiri(open(url))
		price = doc.search('h2').to_s[/\$(\d+)/].gsub('$',"")
		title = doc.title
		description = doc.search('#userbody').to_s.split('<!--')[0].gsub(%r{</?[^>]+?>}, '').gsub(/\n/," ").strip
		if doc.to_s.match('maps.google.com')
			map_url = doc.search('small a')[0]['href'].match('maps.google.com').string
		end
		{ :price => price , :title => title, :description => description, :map_url => map_url }
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'open-uri'

  def index
    @products = Product.all
  end

  def up_vote
    @product = Product.find(params[:id])
    @product.votes += 1
    if @product.save
		  flash[:notice] = "Success! Your product has been saved."
		  redirect_to :action => 'index'
	  end
  end

  def down_vote
    @product = Product.find(params[:id])
    @product.votes -= 1
    @product.save
    if @product.save
	  	flash[:notice] = "Success! Your product has been saved."
		  redirect_to :action => 'index'
	  end
  end

	def show
	  @product = Product.find(params[:id])
	end

	def new
	  @product = Product.new
	end

	def create
		if params['url']
		  @product = Product.new_from_url(params['url'])
   	  if @product.save
		 	  flash[:notice] = "Success! Your product has been saved."
			  redirect_to @product
		  else
		  	render :action => 'new'
		  end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picker</title>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/products/index.html.erb
<div id="prospects" class="span16">
<h2>The Prospects</h2>
<% @products.each do |product| %>
<div class="row">
  <div class="span8">
    $<%= product.price %>
    <%= product.title %>
    <% if product.map_url %>
      <a href=<%= product.map_url %>>Google Map</a>
    <% else %>
      No Map
    <% end %>
    <div id="vote" class="span6">
      <%= link_to "Yes", up_vote_product_path(product.id) %></a>
      <%= link_to "No", down_vote_product_path(product.id)%></a>
    </div>
    <div id=vote-<%= product.id %> class="span2">Score: <%= product.votes %></div>
  </div>
  <div class="span8">
    <%= product.description %>
  </div>
    <% if product.images.present? %>
      <% product.images.each do |image| %>
        <%= image_tag(image) %>
      <% end %>
    <% end %>
</div>
<br /><br />
<% end %>
</div>

app/views/products/new.html.erb
<%= form_tag('/products') do -%>
  <%= text_field_tag 'url' %>
  <%= submit_tag 'Add House' %>
<% end -%>

app/views/products/show.html.erb
<div>
  <div>
$<%= @product.price %>
<%= @product.title %>
<% if @product.map_url %>
  <a href=<%= @product.map_url %>>Google Map</a>
<% else %>
  No Map
<% end %>
</div>
<%= @product.description %>
</div>